export const Motivation = () => { //Coffee and motivational quotes

    const motivationAPI = [
        "I judge a restaurant by the bread and by the coffee.",
        "I like my coffee with cream and my literature with optimism.",
        "You make good coffee... you're a slob, but you make good coffee.",
        "Decaf? No, it's dangerous to dilute my caffeine.",
        "I don't drink coffee to wake up. I wake up to drink coffee.",
        "Three cups of coffee a day keeps the doctor away!",
        "Coffee, because adulting is hard.",
        "Coffee is the common man's gold, and like gold, it brings to every person the feeling of luxury and nobility.",
        "Coffee, the favorite drink of the civilized world.",
        "My coffee machine is the most beautiful person in the world to me.",
        "Seven days without coffee makes one WEAK.",
        "Coffee is a beverage that puts one to sleep when not drank.",
        "Everyone should believe in something. I believe I will have another coffee.",
        "I never drink coffee at lunch. I find it keeps me awake for the afternoon.",
        "But even a bad cup of coffee is better than no coffee at all.",
        "What goes best with a cup of coffee? Another cup.",
        "The most dangerous drinking game is seeing how long I can go without coffee.",
        "Caffeine and sugar, the two basic food groups.",
        "Black as the devil, hot as hell, pure as an angel, sweet as love.",
        "It’s amazing how the world begins to change through the eyes of a cup of coffee.",
        "I want someone to look at me the way I look at coffee.",
        "May your coffee kick in before reality does.",
        "As long as there was coffee in the world, how bad could things be?",
        "The powers of a man’s mind are directly proportional to the quantity of coffee he drinks.",
        "I never laugh until I’ve had my coffee.",
        "Without my morning coffee, I’m just like a dried-up piece of goat.",
        "I believe humans get a lot done, not because we’re smart, but because we have thumbs so we can make coffee.",
        "Life without coffee is like something without something … sorry, I haven’t had any coffee yet.",
        "Decaf coffee only works if you throw it at people.",
        "I'd rather take coffee than compliments just now.",
        "Behind every successful woman is a substantial amount of coffee.",
        "A bad day with coffee is better than a good day without it.",
        "I like my coffee like I like myself: strong, sweet, and too hot for you.",
        "I would rather suffer with coffee than be senseless.",
        "To make me happy: Make me coffee, bring me coffee, be coffee …coffee.",
        "Wanna hear a joke? Decaf.",
        "If you are not coffee, chocolate or bacon, I’m going to need you to go away.",
        "Love is in the air, and it smells like coffee.",
        "No matter what historians claimed, BC really stood for ‘Before Coffee.",
        "Sometimes I go hours without drinking coffee. It’s called sleeping.",
        "May your coffee be strong and your Monday be short.",
        "I have measured out my life with coffee spoons.",
        "Coffee is like a drink of the gods. It brings me back to life.",
        "You can never have too much coffee. I mean, I've never met a coffee I didn't like.",
        "Coffee is a little cup of love and a day of happiness.",
        "Coffee is my good morning.",
        "You can't have a bad day when you start your morning with coffee.",
        "Coffee and friends are treasures that go together.",
        "Only a good friend knows exactly what you like in your coffee.",
        "Life truly begins after the first glorious sip.",
        "Make it better. Have a cup of coffee.",
        "My personality comes alive after my morning coffee.",
        "To get through, I need my morning brew."
    ];

    return (motivationAPI[Math.floor(Math.random() * motivationAPI.length)]);
}